version: 2

jobs:
  build-lint-test:
    working_directory: ~/dependency_spy
    docker:
      - image: circleci/ruby:2.3.7
    steps:
      - checkout

      - name: Restore cache
        type: cache-restore
        key: yavdb-{{ checksum "Gemfile.lock" }}

      - name: Bundle Install
        type: shell
        command: |
          sudo gem update --system
          bundle install --path /tmp/vendor/bundle

      - name: Save cache
        type: cache-save
        key: yavdb-{{ checksum "Gemfile.lock" }}
        paths:
          - /tmp/vendor/bundle

      - name: Vulnerable dependencies
        type: shell
        command: bundle exec depspy check --files Gemfile,Gemfile.lock

      - name: Rubocop
        type: shell
        command: bundle exec rubocop

      - name: Tests
        type: shell
        command: bundle exec rake

workflows:
  version: 2
  test-and-publish:
    jobs:
      - build-lint-test
